name: cancer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=2.106
  - bleach=3.3.0
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - cffi=1.14.5
  - colorama=0.4.4
  - cudatoolkit=10.2.89
  - debugpy=1.3.0
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - freetype=2.10.4
  - icu=68.1
  - importlib-metadata=4.6.1
  - intel-openmp=2021.3.0
  - ipykernel=6.0.1
  - ipython=7.25.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.1
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - lcms2=2.12
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libdeflate=1.7
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.3.0
  - libuv=1.41.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2020.4
  - msys2-conda-epoch=20160418
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - ninja=1.10.2
  - notebook=6.4.0
  - numpy=1.21.0
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=21.0
  - pandoc=2.14.0.3
  - pandocfilters=1.4.2
  - parso=0.8.2
  - pickleshare=0.7.5
  - pillow=8.3.0
  - pip=21.1.3
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.19
  - prompt_toolkit=3.0.19
  - pycparser=2.20
  - pygments=2.9.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - python=3.9.5
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytorch=1.9.0
  - pywin32=300
  - pywinpty=1.1.3
  - pyzmq=22.1.0
  - qt=5.12.9
  - qtconsole=5.1.1
  - qtpy=1.9.0
  - send2trash=1.7.1
  - setuptools=49.6.0
  - six=1.16.0
  - sqlite=3.36.0
  - terminado=0.10.1
  - testpath=0.5.0
  - tk=8.6.10
  - torchaudio=0.9.0
  - torchvision=0.2.2
  - tornado=6.1
  - traitlets=5.0.5
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - ucrt=10.0.20348.0
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - adaptdl==0.2.7
    - autograd==1.3
    - chardet==4.0.0
    - click==8.0.1
    - configparser==5.0.2
    - cycler==0.10.0
    - docker-pycreds==0.4.0
    - future==0.18.2
    - gitdb==4.0.7
    - gitpython==3.1.18
    - grad-cam==1.2.9
    - idna==2.10
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - matplotlib==3.4.2
    - opencv-python==4.5.3.56
    - pandas==1.3.0
    - pathtools==0.1.2
    - portpicker==1.4.0
    - promise==2.3
    - protobuf==3.17.3
    - psutil==5.8.0
    - pytz==2021.1
    - pyyaml==5.4.1
    - redis==3.5.3
    - requests==2.25.1
    - scikit-learn==0.24.2
    - scipy==1.7.0
    - semver==2.13.0
    - sentry-sdk==1.1.0
    - shortuuid==1.0.1
    - smmap==4.0.0
    - split-folders==0.4.3
    - subprocess32==3.5.4
    - threadpoolctl==2.1.0
    - tqdm==4.61.2
    - ttach==0.0.3
    - urllib3==1.25.11
    - wandb==0.10.33
